---
- name: add mysql config
  copy: src=my.cnf dest=/etc/mysql/
  notify:
    - restart mysql

- name: install mysql
  apt: pkg={{ item }} state=installed
  with_items:
    - mysql-server
    - python-mysqldb
  notify:
    - start mysql

- name: update mysql root password
  mysql_user: name=root host=localhost password={{ mysql_root_password }}

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf dest=~/.my.cnf mode=0600

- name: update mysql root password for all other root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
